FROM but5gera/netapp_base_mmcv_gpu:0.1.3

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Prague

RUN wget -c https://download.openmmlab.com/mmdetection/v2.0/yolo/yolov3_mobilenetv2_320_300e_coco/yolov3_mobilenetv2_320_300e_coco_20210719_215349-d18dff72.pth -O "/root/mmdetection/configs/yolo/yolov3_mobilenetv2_320_300e_coco_20210719_215349-d18dff72.pth"

ENTRYPOINT ["/root/start.sh"]

RUN apt-get update \
    && apt-get install -y \
    python3-pip \
    python-is-python3 \
    ffmpeg

COPY python/era_5g_train_detection_standalone /root/era_5g_train_detection_standalone

RUN cd /root/era_5g_train_detection_standalone \
	&& pip3 install -r requirements.txt 
	
ENV PYTHONPATH=/root/era_5g_train_detection_standalone

COPY docker/era_5g_train_detection_standalone/start.sh /root/start.sh

RUN chmod +x /root/start.sh

ENV NETAPP_MODEL_VARIANT=yolov3_mobilenet
ENV NETAPP_TORCH_DEVICE=cuda:0
	
EXPOSE 5896
	
